<img src = "https://drive.google.com/uc?export=view&id=1vU_Lg5LD6Dn521znF_9E6OsJgwptOT9E" alt = "Encabezado MLDS" width = "100%">  </img>

# **Entendimiento de los Datos**
---

Este notebook es una plantilla que le puede servir como guía para el segundo entregable del proyecto aplicado.

## **0. Integrantes del equipo de trabajo**
---

Por favor incluya los nombres completos y número de identificación de los integrantes del equipo de trabajo:

1. ---**JESUS DAVID ESCOBAR DIZZ**---
2. ---**DIANA CELIA ZAMBRANO PINTO**---
3. ---**JUAN DAVID TULANDE GUTIERREZ**---

## **1. Carga de datos**
---
Proporcione únicamente el código de Python necesario para descargar el conjunto de datos que será utilizado en el proyecto. Si es necesario, realice operaciones de adquisición e integración del conjunto de datos.

Como primer paso cargamos las librerias necesarias tanto para leer los datos como para realizar los análisis posteriores pertinentes

In [1]:
import pandas as pd
import numpy as np

Luego cargamos el dataset, donde se le hacen cambios de nombres y tipos para algunas columas

In [2]:
url = "https://github.com/jdizz0414/Data/raw/refs/heads/main/Eventos%20en%20Salud%202025%20en%20Crudo.xlsx"

df = pd.read_excel(url,dtype={"código divipola": str,"código divipola.1": str, "CIE-10": str})
df = df.rename(columns={ "fecha de registro": "FECHA REGISTRO","código divipola": "COD DIVIPOLA DEPARTAMENTO",
                        "departamento": "DEPARTAMENTO","código divipola.1": "COD DIVIPOLA MUN",
                        "municipio": "MUNICIPIO", "municipio": "MUNICIPIO",
                         "sistema": "SISTEMA", "entidad reporta": "ENTIDAD REPORTA"})
df.head()

,FECHA REGISTRO,COD DIVIPOLA DEPARTAMENTO,DEPARTAMENTO,COD DIVIPOLA MUN,MUNICIPIO,CIE-10,NOMBRE,DESCRIPCION,SISTEMA,ENTIDAD REPORTA
0,2025-01-07,08,ATLÁNTICO,08001,BARRANQUILLA,M199,"ARTROSIS, NO ESPECIFICADA",OTRAS ARTROSIS,RIPS,INS
1,2025-01-10,08,ATLÁNTICO,08001,BARRANQUILLA,B07X,VERRUGAS VIRICAS,VERRUGAS VIRICAS,RIPS,EAPB
2,2025-01-13,08,ATLÁNTICO,08001,BARRANQUILLA,B07X,VERRUGAS VIRICAS,VERRUGAS VIRICAS,INS,EAPB
3,2025-01-24,08,ATLÁNTICO,08001,BARRANQUILLA,B07X,VERRUGAS VIRICAS,VERRUGAS VIRICAS,RIPS,INS
4,2025-01-24,08,ATLÁNTICO,08001,BARRANQUILLA,B07X,VERRUGAS VIRICAS,VERRUGAS VIRICAS,INS,EAPB

Luego se carga informacion sobre algunas caracteristicas relevantes que ofrece la OMS sobre las diferentes enfermedad, caracteristicas como :


*   Contagiosa:  Si cuando existe un mecanismo reconocido de transmision entre personas: directo (contacto, respiratorio, sexual), indirecto (fecal-oral, sangre y hemoderivados), vertical de madre a hijo, o por vector cuando el ser humano es reservorio del agente
*   Crónica: Si cuando la HISTORIA NATURAL de la condicion, no su tratamiento, es de larga duracion: persiste tipicamente mas de seis meses, es recurrente por definicion, o requiere manejo indefinido.
*   Mortalidad: Cada nivel se anclo a la letalidad esperada de la condicion (case fatality rate) en condiciones de atencion habituales, o a la supervivencia relativa a cinco años cuando se trata de tumores malignos:1 = muy baja: letalidad por debajo de 0,1%, o supervivencia a 5 años superior al 95%, 2 = baja: letalidad entre 0,1% y 1%, o supervivencia a 5 años entre 80% y 95%, 3 = moderada: letalidad entre 1% y 10%, o supervivencia a 5 años entre 50% y 80%,  4 = alta: letalidad entre 10% y 50%, o supervivencia a 5 años entre 20% y 50%, 5 = muy alta: letalidad superior al 50%, o supervivencia a 5 años inferior al 20%

Se quiere cruzar la informacion del dataset original con la obtenida en la OMS con el fin de añadir informacion relevante al dataset

In [3]:
url2 = "https://github.com/jdizz0414/Data/raw/refs/heads/main/Tabla%20auxiliar%20COD%20CIE10.xlsx"

df_aux = pd.read_excel(url2,dtype={"codigo_cie10 	": str,"mortalidad_1_5": str})
df_aux = df_aux.rename(columns={ "codigo_cie10": "CIE-10","enfermedad": "NOMBRE","contagiosa": "CONTAGIOSA",
                         "cronica": "CRONICA", "mortalidad_1_5": "MORTALIDAD"})
df_aux.head()

,CIE-10,NOMBRE,GRUPO,CONTAGIOSA,CRONICA,MORTALIDAD
0,A000,"COLERA DEBIDO A VIBRIO CHOLERAE 01, BIOTIPO CH...",CIERTAS ENFERMEDADES INFECCIOSAS Y PARASITARIAS,Si,No,3
1,A001,"COLERA DEBIDO A VIBRIO CHOLERAE 01, BIOTIPO EL...",CIERTAS ENFERMEDADES INFECCIOSAS Y PARASITARIAS,Si,No,3
2,A009,"COLERA, NO ESPECIFICADO",CIERTAS ENFERMEDADES INFECCIOSAS Y PARASITARIAS,Si,No,3
3,A010,FIEBRE TIFOIDEA,CIERTAS ENFERMEDADES INFECCIOSAS Y PARASITARIAS,Si,No,3
4,A011,FIEBRE PARATIFOIDEA A,CIERTAS ENFERMEDADES INFECCIOSAS Y PARASITARIAS,Si,No,3

Ahora se hace la union de las dos bases de datos

In [4]:
df_compacto = df.merge(df_aux[["CIE-10","GRUPO","CONTAGIOSA", "CRONICA", "MORTALIDAD"]],on="CIE-10",how="left")
df_compacto.head()

,FECHA REGISTRO,COD DIVIPOLA DEPARTAMENTO,DEPARTAMENTO,COD DIVIPOLA MUN,MUNICIPIO,CIE-10,NOMBRE,DESCRIPCION,SISTEMA,ENTIDAD REPORTA,GRUPO,CONTAGIOSA,CRONICA,MORTALIDAD
0,2025-01-07,08,ATLÁNTICO,08001,BARRANQUILLA,M199,"ARTROSIS, NO ESPECIFICADA",OTRAS ARTROSIS,RIPS,INS,ENFERMEDADES DEL SISTEMA OSTEOMUSCULAR Y DEL T...,No,Si,1
1,2025-01-10,08,ATLÁNTICO,08001,BARRANQUILLA,B07X,VERRUGAS VIRICAS,VERRUGAS VIRICAS,RIPS,EAPB,CIERTAS ENFERMEDADES INFECCIOSAS Y PARASITARIAS,Si,No,1
2,2025-01-13,08,ATLÁNTICO,08001,BARRANQUILLA,B07X,VERRUGAS VIRICAS,VERRUGAS VIRICAS,INS,EAPB,CIERTAS ENFERMEDADES INFECCIOSAS Y PARASITARIAS,Si,No,1
3,2025-01-24,08,ATLÁNTICO,08001,BARRANQUILLA,B07X,VERRUGAS VIRICAS,VERRUGAS VIRICAS,RIPS,INS,CIERTAS ENFERMEDADES INFECCIOSAS Y PARASITARIAS,Si,No,1
4,2025-01-24,08,ATLÁNTICO,08001,BARRANQUILLA,B07X,VERRUGAS VIRICAS,VERRUGAS VIRICAS,INS,EAPB,CIERTAS ENFERMEDADES INFECCIOSAS Y PARASITARIAS,Si,No,1

## **2. Análisis Exploratorio de los Datos**
---

Normalmente en el análisis exploratorio, se trata de dar respuesta a los siguientes elementos:

### **2.1. Resumen General**
---

- ¿Cuántos registros contiene el *dataset*?

Al obtener la informacion del dataset por medio de .info(), el número de registros del conjunto de datos es de 415.154

- ¿En qué formato están guardados los datos?

Como se observa en la linea de codigo que trae la informacion desde el repositorio, el formato de los datos es .xlsx

- ¿Qué tamaño en MB tiene el conjunto de datos?

El .info() también arroja esta información, y corresponde a 44.3 MB

In [5]:
df_compacto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 415154 entries, 0 to 415153
Data columns (total 14 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   FECHA REGISTRO             415154 non-null  datetime64[ns]
 1   COD DIVIPOLA DEPARTAMENTO  415154 non-null  object
 2   DEPARTAMENTO               415154 non-null  object
 3   COD DIVIPOLA MUN           415154 non-null  object
 4   MUNICIPIO                  415154 non-null  object
 5   CIE-10                     415136 non-null  object
 6   NOMBRE                     415135 non-null  object
 7   DESCRIPCION                415135 non-null  object
 8   SISTEMA                    415154 non-null  object
 9   ENTIDAD REPORTA            415154 non-null  object
 10  GRUPO                      415135 non-null  object
 11  CONTAGIOSA                 415135 non-null  object
 12  CRONICA                    415135 non-null  object
 13  MORTALIDAD                 415135 non-null  object
dtypes: datetime64[ns](1), object(13)
memory usage: 44.3+ MB

### **2.2. Análisis estadístico descriptivo**
---

Describa el conjunto de datos por medio de estadística descriptiva, aportando interpretaciones precisas que ayuden a entender los datos.

In [6]:
columnas_excluir = ["CIE-10", "NOMBRE", "DESCRIPCION"]

for columna in df_compacto.select_dtypes(include="object").columns:

    if columna not in columnas_excluir:

        frecuencia = df_compacto[columna].value_counts()
        proporcion = df_compacto[columna].value_counts(normalize=True) * 100

        tabla = pd.DataFrame({"Frecuencia": frecuencia,"Proporción (%)": proporcion.round(2)})

        tabla.loc["TOTAL"] = [tabla["Frecuencia"].sum(),100.00]

        print("\n", columna)
        print(tabla)

 COD DIVIPOLA DEPARTAMENTO
                           Frecuencia  Proporción (%)
COD DIVIPOLA DEPARTAMENTO
76                           134134.0           32.31
08                            57442.0           13.84
13                            40919.0            9.86
41                            35193.0            8.48
11                            34692.0            8.36
05                            29163.0            7.02
68                            22843.0            5.50
47                            22142.0            5.33
25                            12812.0            3.09
73                             6985.0            1.68
63                             4829.0            1.16
17                             4244.0            1.02
66                             3153.0            0.76
52                             2014.0            0.49
15                             1726.0            0.42
20                             1724.0            0.42
19                              633.0            0.15
50                              381.0            0.09
54                              122.0            0.03
44                                3.0            0.00
TOTAL                        415154.0          100.00

 DEPARTAMENTO
                    Frecuencia  Proporción (%)
DEPARTAMENTO
VALLE DEL CAUCA       134134.0           32.31
ATLÁNTICO              57442.0           13.84
BOLÍVAR                40919.0            9.86
HUILA                  35193.0            8.48
BOGOTÁ, D.C.           34692.0            8.36
ANTIOQUIA              29163.0            7.02
SANTANDER              22843.0            5.50
MAGDALENA              22142.0            5.33
CUNDINAMARCA           12812.0            3.09
TOLIMA                  6985.0            1.68
QUINDÍO                 4829.0            1.16
CALDAS                  4244.0            1.02
RISARALDA               3153.0            0.76
NARIÑO                  2014.0            0.49
BOYACÁ                  1726.0            0.42
CESAR                   1724.0            0.42
CAUCA                    633.0            0.15
META                     381.0            0.09
NORTE DE SANTANDER       122.0            0.03
LA GUAJIRA                 3.0            0.00
TOTAL                 415154.0          100.00

 COD DIVIPOLA MUN
                  Frecuencia  Proporción (%)
COD DIVIPOLA MUN
76001                92234.0           22.22
08001                56518.0           13.61
13001                40916.0            9.86
41001                35193.0            8.48
11001                34692.0            8.36
...                      ...             ...
76126                    1.0            0.00
15407                    1.0            0.00
19548                    1.0            0.00
08078                    1.0            0.00
TOTAL               415154.0          100.00

[99 rows x 2 columns]

 MUNICIPIO
                     Frecuencia  Proporción (%)
MUNICIPIO
SANTIAGO DE CALI        92234.0           22.22
BARRANQUILLA            56518.0           13.61
CARTAGENA DE INDIAS     40916.0            9.86
NEIVA                   35193.0            8.48
BOGOTÁ, D.C.            34692.0            8.36
...                         ...             ...
CALIMA                      1.0            0.00
VILLA DE LEYVA              1.0            0.00
PIENDAMÓ - TUNÍA            1.0            0.00
BARANOA                     1.0            0.00
TOTAL                  415154.0          100.00

[99 rows x 2 columns]

 SISTEMA
          Frecuencia  Proporción (%)
SISTEMA
RIPS        207461.0           49.97
INS         124410.0           29.97
SIVIGILA     83283.0           20.06
TOTAL       415154.0          100.00

 ENTIDAD REPORTA
                 Frecuencia  Proporción (%)
ENTIDAD REPORTA
EAPB               207617.0           50.01
IPS                124681.0           30.03
INS                 82856.0           19.96
TOTAL              415154.0          100.00

 GRUPO
                                                    Frecuencia  Proporción (%)
GRUPO
ENFERMEDADES DEL APARATO CIRCULATORIO                  97102.0           23.39
FACTORES QUE INFLUYEN EN EL ESTADO DE SALUD Y C...     52235.0           12.58
ENFERMEDADES ENDOCRINAS, NUTRICIONALES Y METABÓ...     39107.0            9.42
\tENFERMEDADES DEL APARATO DIGESTIVO                   33816.0            8.15
ENFERMEDADES DEL SISTEMA OSTEOMUSCULAR Y DEL TE...     32707.0            7.88
SÍNTOMAS, SIGNOS Y HALLAZGOS ANORMALES CLÍNICOS...     23779.0            5.73
ENFERMEDADES DEL APARATO GENITOURINARIO                22089.0            5.32
TRASTORNOS MENTALES Y DEL COMPORTAMIENTO               21593.0            5.20
ENFERMEDADES DEL SISTEMA NERVIOSO                      18322.0            4.41
ENFERMEDADES DEL APARATO RESPIRATORIO                  14429.0            3.48
NEOPLASIAS                                             11968.0            2.88
ENFERMEDADES DEL OÍDO Y DE LA APÓFISIS MASTOIDES       10411.0            2.51
CIERTAS ENFERMEDADES INFECCIOSAS Y PARASITARIAS         9677.0            2.33
TRAUMATISMOS, ENVENENAMIENTOS Y ALGUNAS OTRAS C...      9490.0            2.29
ENFERMEDADES DE LA PIEL Y EL TEJIDO SUBCUTÁNEO          7588.0            1.83
ENFERMEDADES DEL OJO Y SUS ANEXOS                       7201.0            1.73
ENFERMEDADES DE LA SANGRE Y DE LOS ÓRGANOS HEMA...      2005.0            0.48
CAUSAS EXTERNAS DE MORBILIDAD Y DE MORTALIDAD           1114.0            0.27
MALFORMACIONES CONGÉNITAS, DEFORMIDADES Y ANOMA...       421.0            0.10
EMBARAZO, PARTO Y PUERPERIO                               46.0            0.01
CÓDIGOS PARA SITUACIONES ESPECIALES                       18.0            0.00
CIERTAS AFECCIONES ORIGINADAS EN EL PERIODO PER...        17.0            0.00
TOTAL                                                 415135.0          100.00

 CONTAGIOSA
            Frecuencia  Proporción (%)
CONTAGIOSA
No            400343.0           96.44
Si             14792.0            3.56
TOTAL         415135.0          100.00

 CRONICA
         Frecuencia  Proporción (%)
CRONICA
Si         303871.0            73.2
No         111264.0            26.8
TOTAL      415135.0           100.0

 MORTALIDAD
            Frecuencia  Proporción (%)
MORTALIDAD
1             190893.0           45.98
2             136181.0           32.80
3              51528.0           12.41
4              30639.0            7.38
5               5894.0            1.42
TOTAL         415135.0          100.00

AL tratarse de variables categoricas, se hicieron tablas de frecuencia para las vaiables representativas del dataset donde se pueden observar la distribucion de las categorias

### **2.3. Resumen de la Calidad de los datos**
---

- ¿Se detecta la ausencia de datos, la presencia de datos erróneos o la existencia de datos de baja calidad en el conjunto?

Se identifico un solo registro con codificacion errada, el cual debe sacarle del dataset

In [7]:
#REGISTROS CODIFICADOS ERRADAMENTE
df_filtrado = df_compacto[ df_compacto["CIE-10"].notna() & df_compacto["DESCRIPCION"].isna()]
df_filtrado

,FECHA REGISTRO,COD DIVIPOLA DEPARTAMENTO,DEPARTAMENTO,COD DIVIPOLA MUN,MUNICIPIO,CIE-10,NOMBRE,DESCRIPCION,SISTEMA,ENTIDAD REPORTA,GRUPO,CONTAGIOSA,CRONICA,MORTALIDAD
185050,2025-08-13 10:15:00,11,"BOGOTÁ, D.C.",11001,"BOGOTÁ, D.C.",N39X,NaN,NaN,RIPS,IPS,NaN,NaN,NaN,NaN

- ¿Se identifican registros con datos ilegibles o con dificultades de codificación durante la revisión del conjunto de datos?

No se ven problemas graves de codificación de caracteres o texto ilegible. Las columnas contienen una estandarización en cada una de las columnas, se respetan las tildes y los caracteres especiales, como en Atlántico o Bogotá, D.C. Además, los códigos territoriales (código divipola) y los códigos internacionales de enfermedades (CIE-10) siguen de forma estricta la estructura alfanumérica del catálogo oficial.

- ¿Se observa una diversidad de formatos en el conjunto de datos que pueda dificultar su consistencia o comprensión?

La estructura de los datos en la mayoría de los datos no representa la realidad de este mismo, la mayoría de la columna del Conjunto de datos son de tipo categóricas, por lo que esencial cambiar este tipo de columnas a tipo texto (String)
- ¿Se identificaron y abordaron posibles problemas, como valores atípicos, duplicados o datos faltantes?

Se encontraron datos 18 datos faltantes, los cuales representan una proporcion no representativa dentro del conjunto de datos y se deben excluir de los analisis posteriores.

Se encontró un volumen crítico de 78.896 filas duplicadas exactas; esto representa el 19.00% del total del dataset. Son registros de salud que coinciden exactamente en fecha, ubicación, diagnóstico y entidad. Se deben eliminar estos registros repetidos para evitar sesgos por contar de más en las frecuencias diagnósticas.

Al tratarse de variables categóricas no se observan valores atipicos, se evidencian categorias con mucha o poca frecuencia que pueden generar desbalanceos o que pueden orientar el comportamiento de un determinada categoria para lo cual se puede hacer analisis mas profundos de la naturaleza de estas, por ejemplo el código I10X (Hipertensión esencial) aparece 72,598 veces lo que representa el 17.48% de la data que puede verse en este contexto como un pico epidemiologico (puede estar o no relacionada con condiciones ambientales o geograficas determinadas por las variables de georeferencia)

In [8]:
#REGISTROS CON DATOS FALTANTES:
df_compacto[df_compacto[["CIE-10"]].isna().any(axis=1)]

,FECHA REGISTRO,COD DIVIPOLA DEPARTAMENTO,DEPARTAMENTO,COD DIVIPOLA MUN,MUNICIPIO,CIE-10,NOMBRE,DESCRIPCION,SISTEMA,ENTIDAD REPORTA,GRUPO,CONTAGIOSA,CRONICA,MORTALIDAD
287806,2025-09-07 19:00:00,76,VALLE DEL CAUCA,76109,BUENAVENTURA,NaN,NaN,NaN,RIPS,EAPB,NaN,NaN,NaN,NaN
290960,2025-09-04 19:00:00,76,VALLE DEL CAUCA,76109,BUENAVENTURA,NaN,NaN,NaN,RIPS,INS,NaN,NaN,NaN,NaN
290961,2025-09-05 19:00:00,76,VALLE DEL CAUCA,76109,BUENAVENTURA,NaN,NaN,NaN,RIPS,EAPB,NaN,NaN,NaN,NaN
290962,2025-09-06 19:00:00,76,VALLE DEL CAUCA,76109,BUENAVENTURA,NaN,NaN,NaN,INS,IPS,NaN,NaN,NaN,NaN
290963,2025-09-09 19:00:00,76,VALLE DEL CAUCA,76109,BUENAVENTURA,NaN,NaN,NaN,INS,EAPB,NaN,NaN,NaN,NaN
290964,2025-09-10 19:00:00,76,VALLE DEL CAUCA,76109,BUENAVENTURA,NaN,NaN,NaN,RIPS,IPS,NaN,NaN,NaN,NaN
290965,2025-09-11 19:00:00,76,VALLE DEL CAUCA,76109,BUENAVENTURA,NaN,NaN,NaN,SIVIGILA,EAPB,NaN,NaN,NaN,NaN
290966,2025-09-13 19:00:00,76,VALLE DEL CAUCA,76109,BUENAVENTURA,NaN,NaN,NaN,INS,EAPB,NaN,NaN,NaN,NaN
290967,2025-09-15 19:00:00,76,VALLE DEL CAUCA,76109,BUENAVENTURA,NaN,NaN,NaN,RIPS,EAPB,NaN,NaN,NaN,NaN
290968,2025-09-16 19:00:00,76,VALLE DEL CAUCA,76109,BUENAVENTURA,NaN,NaN,NaN,RIPS,INS,NaN,NaN,NaN,NaN
290969,2025-09-18 19:00:00,76,VALLE DEL CAUCA,76109,BUENAVENTURA,NaN,NaN,NaN,SIVIGILA,IPS,NaN,NaN,NaN,NaN
290970,2025-09-20 19:00:00,76,VALLE DEL CAUCA,76109,BUENAVENTURA,NaN,NaN,NaN,SIVIGILA,INS,NaN,NaN,NaN,NaN
290971,2025-09-20 19:00:00,76,VALLE DEL CAUCA,76109,BUENAVENTURA,NaN,NaN,NaN,SIVIGILA,EAPB,NaN,NaN,NaN,NaN
290972,2025-09-23 19:00:00,76,VALLE DEL CAUCA,76109,BUENAVENTURA,NaN,NaN,NaN,INS,IPS,NaN,NaN,NaN,NaN
290973,2025-09-24 19:00:00,76,VALLE DEL CAUCA,76109,BUENAVENTURA,NaN,NaN,NaN,SIVIGILA,EAPB,NaN,NaN,NaN,NaN
290974,2025-09-25 19:00:00,76,VALLE DEL CAUCA,76109,BUENAVENTURA,NaN,NaN,NaN,INS,IPS,NaN,NaN,NaN,NaN
290975,2025-09-27 19:00:00,76,VALLE DEL CAUCA,76109,BUENAVENTURA,NaN,NaN,NaN,INS,EAPB,NaN,NaN,NaN,NaN
290976,2025-09-29 19:00:00,76,VALLE DEL CAUCA,76109,BUENAVENTURA,NaN,NaN,NaN,RIPS,INS,NaN,NaN,NaN,NaN

In [9]:
# REGISTROS REPETIDOS
registros_repetidos = df_compacto[df_compacto.duplicated(keep=False)]
registros_repetidos

,FECHA REGISTRO,COD DIVIPOLA DEPARTAMENTO,DEPARTAMENTO,COD DIVIPOLA MUN,MUNICIPIO,CIE-10,NOMBRE,DESCRIPCION,SISTEMA,ENTIDAD REPORTA,GRUPO,CONTAGIOSA,CRONICA,MORTALIDAD
22,2025-02-28 00:00:00,47,MAGDALENA,47001,SANTA MARTA,B07X,VERRUGAS VIRICAS,VERRUGAS VIRICAS,RIPS,INS,CIERTAS ENFERMEDADES INFECCIOSAS Y PARASITARIAS,Si,No,1
23,2025-02-28 00:00:00,47,MAGDALENA,47001,SANTA MARTA,B07X,VERRUGAS VIRICAS,VERRUGAS VIRICAS,RIPS,INS,CIERTAS ENFERMEDADES INFECCIOSAS Y PARASITARIAS,Si,No,1
29,2025-02-22 00:00:00,68,SANTANDER,68001,BUCARAMANGA,B07X,VERRUGAS VIRICAS,VERRUGAS VIRICAS,RIPS,EAPB,CIERTAS ENFERMEDADES INFECCIOSAS Y PARASITARIAS,Si,No,1
30,2025-02-22 00:00:00,68,SANTANDER,68001,BUCARAMANGA,B07X,VERRUGAS VIRICAS,VERRUGAS VIRICAS,RIPS,EAPB,CIERTAS ENFERMEDADES INFECCIOSAS Y PARASITARIAS,Si,No,1
31,2025-02-22 00:00:00,68,SANTANDER,68001,BUCARAMANGA,B07X,VERRUGAS VIRICAS,VERRUGAS VIRICAS,RIPS,EAPB,CIERTAS ENFERMEDADES INFECCIOSAS Y PARASITARIAS,Si,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
414359,2025-12-12 10:00:00,68,SANTANDER,68001,BUCARAMANGA,I10X,HIPERTENSION ESENCIAL (PRIMARIA),HIPERTENSION ESENCIAL (PRIMARIA),RIPS,EAPB,ENFERMEDADES DEL APARATO CIRCULATORIO,No,Si,2
414442,2025-12-05 11:00:00,68,SANTANDER,68001,BUCARAMANGA,I10X,HIPERTENSION ESENCIAL (PRIMARIA),HIPERTENSION ESENCIAL (PRIMARIA),RIPS,IPS,ENFERMEDADES DEL APARATO CIRCULATORIO,No,Si,2
414725,2025-12-19 14:00:00,68,SANTANDER,68001,BUCARAMANGA,E119,"DIABETES MELLITUS NO INSULINODEPENDIENTE, SIN ...",DIABETES MELLITUS NO INSULINODEPENDIENTE,RIPS,EAPB,"ENFERMEDADES ENDOCRINAS, NUTRICIONALES Y METAB...",No,Si,3
414759,2025-12-05 11:00:00,68,SANTANDER,68001,BUCARAMANGA,I10X,HIPERTENSION ESENCIAL (PRIMARIA),HIPERTENSION ESENCIAL (PRIMARIA),RIPS,IPS,ENFERMEDADES DEL APARATO CIRCULATORIO,No,Si,2
414922,2025-12-22 15:00:00,68,SANTANDER,68001,BUCARAMANGA,I10X,HIPERTENSION ESENCIAL (PRIMARIA),HIPERTENSION ESENCIAL (PRIMARIA),RIPS,EAPB,ENFERMEDADES DEL APARATO CIRCULATORIO,No,Si,2

In [10]:
#VALORES ATIPICOS
tabla_cie10 = (df_compacto["CIE-10"].value_counts().to_frame("Frecuencia"))
tabla_cie10["Proporción (%)"] = (tabla_cie10["Frecuencia"] / df_compacto["CIE-10"].notna().sum() * 100).round(2)
tabla_cie10

        Frecuencia  Proporción (%)
CIE-10
I10X         72598           17.49
E119         11487            2.77
Z000          6309            1.52
Z108          6101            1.47
B349          5345            1.29
...            ...             ...
A318             1            0.00
Q206             1            0.00
C712             1            0.00
H499             1            0.00
B699             1            0.00

[4068 rows x 2 columns]

### **2.4. Tipos de variables**
---

- ¿El conjunto de datos tiene una variable objetivo a estimar?, de ser así, ¿es una variable continúa o categórica?

El conjunto de datos no tiene una variable objetivo a estimar, debido a que se trata esencialmente de eventos en salud, por lo que es un dataset específicamente orientado al análisis exploratorio de datos, analítica descriptica o quizas aprendizaje no supervisado

- Analice la distribución de las etiquetas, identifique si hay desbalanceo de datos.

Se evidencia un desbalance significativo en la distribución de las categorías de la mayoría de las variables del conjunto de datos. La magnitud de este desbalance varía considerablemente dependiendo de la variable seleccionada como etiqueta objetivo (variable dependiente), lo cual puede tener implicaciones importantes en el desempeño y la interpretación de los modelos de clasificación.

• CONTAGIOSA — Desbalance severo (clasificación binaria)
La variable presenta un desbalance marcado entre sus dos categorías. La clase mayoritaria "No" concentra el 96,44 % de los registros, mientras que la clase minoritaria "Sí" representa únicamente el 3,56 %. Esta distribución corresponde a un desbalance severo, que debe ser considerado al desarrollar modelos de clasificación binaria, ya que un modelo podría favorecer la clase mayoritaria y presentar un desempeño deficiente en la identificación de los casos minoritarios.

• MORTALIDAD — Desbalance ordinal (clasificación multiclase)
La distribución de la variable presenta un sesgo positivo, con una mayor concentración de observaciones en los niveles inferiores de mortalidad. El nivel 1 concentra el 45,98 % de los casos, mientras que el nivel 5 representa únicamente el 1,42 %. En términos relativos, existe una proporción superior a 32:1 entre ambos extremos de la escala, evidenciando una distribución considerablemente desigual entre las categorías.

• GRUPO DIAGNÓSTICO — Desbalance multiclase extremo
Esta variable presenta uno de los niveles de desbalance más elevados del conjunto de datos. La categoría "Enfermedades del aparato circulatorio" concentra el 23,39 % del total de registros. En contraste, las cinco categorías con menor frecuencia, consideradas conjuntamente, no alcanzan el 0,05 % de las observaciones. Adicionalmente, se identifican categorías con una representación prácticamente nula; por ejemplo, "Ciertas afecciones originadas en el período perinatal" presenta una proporción reportada de 0,00 %, aunque cuenta con 17 registros.

• CRÓNICA — Desbalance moderado (clasificación binaria)
La variable presenta un desbalance moderado entre sus categorías. La categoría "Sí" representa el 73,20 % de los registros, mientras que la categoría "No" corresponde al 26,80 %. Aunque la diferencia es considerable, el nivel de desbalance es menor que el observado en variables como CONTAGIOSA.

• DEPARTAMENTO y MUNICIPIO — Concentración y sesgo geográfico
Las variables asociadas a la ubicación geográfica presentan una alta concentración de registros en determinadas zonas del país. El departamento del Valle del Cauca concentra el 32,31 % de los registros, mientras que Cali, perteneciente a este departamento, representa el 22,22 % del total de registros correspondientes a municipios. En contraste, algunos departamentos presentan una representación extremadamente baja; por ejemplo, La Guajira cuenta con menos de tres registros.

## **Créditos**
* **Profesor:** [Felipe Restrepo Calle](https://dis.unal.edu.co/~ferestrepoca/)
* **Asistentes docentes:**
    - [Juan Sebastián Lara Ramírez](https://www.linkedin.com/in/juan-sebastian-lara-ramirez-43570a214/).
* **Diseño de imágenes:**
    - [Rosa Alejandra Superlano Esquibel](mailto:rsuperlano@unal.edu.co).
* **Coordinador de virtualización:**
    - [Edder Hernández Forero](https://www.linkedin.com/in/edder-hernandez-forero-28aa8b207/).
    
**Universidad Nacional de Colombia** - *Facultad de Ingeniería*